# Generated by Django 3.1.1 on 2020-09-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('blurInt', models.IntegerField()),
                ('keysession', models.TextField(max_length=200)),
                ('outputPath', models.TextField(max_length=255)),
                ('img', models.ImageField(max_length=254, upload_to='photos/')),
            ],
        ),
    ]
